--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BeeAZ-pm-pl/AcidIsland/AcidIslandPM
build-by-default: true
branches:
- master
projects:
  AcidIslandPM:
    path: ""
    lint: false
...
