config-version: 1

start-item:
 - "325:8:2"
 - "325:10:1"
 - "79:0:2"
 - "360:0:1"
 - "352:0:12"
 - "361:0:1"
 - "81:0:1"
 - "338:0:1"
 - "297:0:1"
 - "296:0:1"
 - "298:0:1"
 - "299:0:1"
 - "300:0:1"
 - "301:0:1"
 
#message
ISLAND-NOTFOUND: "§e§lIsland Not Found"
PLAYER-NOTFOUND: "§e§lPlayer Not Found"
ISLAND-JOIN: "§e§lWelcome to the Island"
ISLAND-CREATE: "§e§lCreate Island Success With Seed {seed}"
ISLAND-ADD: "§e§lAdd Member To Your Island Successfully"
ISLAND-ADDERROR: "§e§lThe Member You Want To Add Already Exists In The List"
ISLAND-DELETE: "§e§lSuccessfully cleared your island"
ISLAND-DELETE-OTHER: "§e§lThis player's island has been successfully deleted"
ISLAND-INFO: "§e§lInfo Island\n§c§lMember {member}\n§c§lPVP {pvp}\n§c§lLOCK: {lock}"
ISLAND-KICK: "§e§lYou have successfully kicked this player off the island"
ISLAND-KICK2: "§e§l You have been kicked off the island"
ISLAND-KICKERROR: "§e§lPlayers Not On Your Island"
ISLAND-REMOVEMEMBER: "§e§lYou have removed this player from your friends list"
ISLAND-REMOVEERROR: "§e§lDo Not Enter Your Own Name"
ISLAND-REMOVEERROR2: "§e§lThe Player You Enter Is Not In Your Friends List"
ISLAND-TELEPORT: "§e§l You have teleported to the island {island}"
ISLAND-TELEPORT-LOCK: "§e§lThis player island is locked"
PVP: "§e§lPvp on"
NOPVP: "§e§lPvp off"
LOCK: "§e§lLock on"
UNLOCK: "§e§lUnlock"
TopCount: 10
TopElement: "{player} with {value} points"